### ISSUE TITLE
Where is the original software?

### ISSUE THREAD

**Issue by RussNelson** [m5stack/M5StickC#107]
Where might I find the source of the code that ships with the M5StickC? It has these modes:

- 3D box rendered according to the accelerometer report.
- reads the RTC and writes it to the screen in a big font.
- scrolling FFT display of the microphone input
- Sending IR data
- BLE connecting.

**Comment by EeeeBin** [comment]
Here:
https://github.com/m5stack/M5StickC/tree/master/examples/Basics/FactoryTest
