### ISSUE TITLE
Flappy Bird Example EEPROM not working

### ISSUE THREAD

**Issue by anthonykeane** [m5stack/M5StickC#11]
The FlappyBird has an example of EEPROM (which I need for my project) this EEPROM value is lost. ie the High Score resets to 0

**Comment by zhouyangyale** [comment]
Yes, we will add

**Comment by Zontex** [comment]
> The FlappyBird has an example of EEPROM (which I need for my project) this EEPROM value is lost. ie the High Score resets to 0

Hi, Quite a delay but I just fixed the EEPROM and updated the file in the repository, you can check it.
