### ISSUE TITLE
I2C not correctly set up

### ISSUE THREAD

**Issue by CoenSchalkwijk** [m5stack/M5StickC#114]
https://github.com/m5stack/M5StickC/blob/1befa455553c965aeb7c91e8515a9f192310f7b4/examples/Unit/CardKB/CardKB.ino#L10

In order for this example to work (this and the joystick example). This line has to be changed to:

`Wire.begin(32, 33);`

**Comment by Zontex** [comment]
> Wire.begin(32, 33);

Hi, I just tested the code and it works both by supplying the SDL / SCL data to Wire library and without (leaving it as default Wire.begin()) both work fine :)
