### ISSUE TITLE
Factory Test incorrectly displays number of APs

### ISSUE THREAD

**Issue by zshivers** [m5stack/M5StickC#12]
These lines contain a printf without any parameter.

https://github.com/m5stack/M5StickC/blob/781128641206017e99f211ee7bb14fce98428259/examples/Basics/FactoryTest/FactoryTest.ino#L54

https://github.com/m5stack/M5StickC/blob/781128641206017e99f211ee7bb14fce98428259/examples/Basics/FactoryTest/FactoryTest.ino#L58

This should be changed to:
`M5.Lcd.printf("%d AP", n);`

Better yet, the commons lines inside the `if` statement should be brought out:
```
    if (n == 0) {
      M5.Lcd.setTextColor(RED, WHITE);
    } else {   
      M5.Lcd.setTextColor(GREEN, WHITE);
    }
    M5.Lcd.setCursor(5, 60, 4);
    M5.Lcd.printf("%d AP", n);
```

**Comment by zhouyangyale** [comment]
ok，thks
