### ISSUE TITLE
IR Pin Clarification

### ISSUE THREAD

**Issue by aenertia** [m5stack/M5StickC#13]
On the Label on the Back of the M5StickC the IR PIN is shown as GPIO10 ... but in the examples and in the matrix on this Page it is shown as GPIO9..

Which is it?

**Comment by zhouyangyale** [comment]
iThe IR pin is always GPIO9,
The back label on my side is also gpio9

**Comment by aenertia** [comment]
Well the Labeling on all of the 11 units I have is wrong then see here for image : https://github.com/aenertia/m5stick-scope-ecg/blob/master/pcb/decon_pcb4.jpg

**Comment by zshivers** [comment]
I can confirm the same is written on my unit.

**Comment by Zontex** [comment]
It seem to be a label issue, it was fixed in newer product  packaging labels. The pin is G9.
