### ISSUE TITLE
In_espi min() conflict with std::bitset

### ISSUE THREAD

**Issue by Sepp62** [m5stack/M5StickC#132]
"min" macro in In_espi.h conflicts with std::bitset

See also:
https://github.com/m5stack/M5StickC/issues/103

Workaround: 
#undef min
#include <%bitset> // remove percent sign, cannot insert text in these parentheses
...

**Comment by Tinyu-Zhao** [comment]
Fixed https://github.com/m5stack/M5StickC/commit/9b92d2781a0e3f6a2d8186884066bd2a1bbf981a
