### ISSUE TITLE
Set millis or nanos for the RTC

### ISSUE THREAD

**Issue by danspage** [m5stack/M5StickC#134]
I did some searching both on the web and in the source code, and could not find a way to set the millis or nanos of the RTC clock. Is there a way to do this currently? My end goal is to sync the RTC with a GPS via a serial connection, so that the clocks on separate M5StickC's will match up accurately.

**Comment by Tinyu-Zhao** [comment]
The RTC chip is the BM8563, which has a maximum accuracy of only seconds.

[DataSheet](https://m5stack.oss-cn-shenzhen.aliyuncs.com/resource/docs/datasheet/core/BM8563_V1.1_cn.pdf)
