### ISSUE TITLE
GetCoulombData doesn't appear to work - always returns 0

### ISSUE THREAD

**Issue by KevWal** [m5stack/M5StickC#143]
Hi

In my code I call EnableCoulombcounter() in setup(), and then call and print M5.Axp.GetCoulombData() each time around loop(), but it doesn't appear to work - it always returns 0.

Another person points out the issue here:
https://forum.m5stack.com/topic/2434/axp192-coulomb-counter-issues

Thanks
Kevin

**Comment by Tinyu-Zhao** [comment]
If you successfully run this function, please allow me to close this issue
