### ISSUE TITLE
Usage of Wire library.

### ISSUE THREAD

**Issue by Koepel** [m5stack/M5StickC#15]
In the files:
- M5StickC/examples/Hat/ENV/DHT12.cpp
- M5StickC/examples/Basics/FactoryTest/DHT12.cpp

These lines are not needed:
```
delay(50);
if (Wire.available()!=0) return 2;
```
Does the sensor need that delay before using other functions ? That delay is not needed for the I2C bus. The line "`if (Wire.available()!=0) return 2;`" is always zero, there is not need to check that.

See also my [alternative explanation of the functions of the Wire library](https://github.com/Koepel/How-to-use-the-Arduino-Wire-library/wiki/Explanation-of-the-functions-of-the-Wire-library).

In the file
- M5StickC/examples/Hat/ENV/bmm150.cpp

all the `Wire.beginTransmission()` before and `Wire.endTransmission()` after a `Wire.requestFrom()` may be removed.
Explanation: [Common-mistakes](https://github.com/Koepel/How-to-use-the-Arduino-Wire-library/wiki/Common-mistakes), number 2 and 3.

**Comment by Zontex** [comment]
Could you please send pull request? we will fix it in the next update, thanks for letting us know!
