### ISSUE TITLE
Platform.io missing versions

### ISSUE THREAD

**Issue by catofstealth** [m5stack/M5StickC#154]
The version on platform.io is currently stuck at 0.2.5 and appears to be because the library.properties version tag is not being maintained across releases (currently still set as 0.2.5 for the last 3 releases)

If this could be automated that would be the best solution otherwise any new releases won't be available via Platform.io unless this is manually updated.

**Comment by Tinyu-Zhao** [comment]
Thank you for the tip, we will update it in the next release
