### ISSUE TITLE
No way to power off external peripherials

### ISSUE THREAD

**Issue by smily77** [m5stack/M5StickC#157]
### Describe the bug

The external power on the groove connector remains when PowerOff() or deepSleep() or what ever there is no possibility to switch it of. Same issue was recently reported for the Core2 library (here: https://github.com/m5stack/M5Core2/issues/99) There it was solved (By the way isn't an issue with the M5StickC-plus library)

### To reproduce

In any environment this is not possible 

### Expected behavior

Switch off the power at the groove connector when is PowerOff() is called or alternative function like PowerOffPeripherials()

### Environment

- OS: Windows
- IDE &IDE Version: Arduino 1.8x
- Repository Version: current

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/m5stack/M5StickC/issues?q=)
- [X] My report contains all necessary details

**Comment by Tinyu-Zhao** [comment]
Thanks for the suggestion, I have added the function to control Port. https://github.com/m5stack/M5StickC/commit/0527606d9e56c956ab17b278c25e3d07d7664f5e

**Comment by M95D** [comment]
You didn't change the version. This modification is not downloaded by Arduino IDE.

**Comment by Tinyu-Zhao** [comment]
> You didn't change the version. This modification is not downloaded by Arduino IDE.

Released.

https://github.com/m5stack/M5StickC/releases/tag/0.2.9

**Comment by M95D** [comment]
That was quick! Thanks.
