### ISSUE TITLE
Software reset

### ISSUE THREAD

**Issue by rigelinorion** [m5stack/M5StickC#158]
Hello. Is there any procedure to restart the m5stick in the library?

**Comment by Tinyu-Zhao** [comment]
You mean restore the factory settings?

**Comment by Tinyu-Zhao** [comment]
Power switch operation:

Power on :Press power button for 2 seconds

Power off :Press power button for 6 seconds

The input range of VBUS_VIN and VBUS_USB is limited to 4.8-5.5V, and the internal battery will be charged through AXP192 power management when VBUS is powered.

**Comment by MDAR** [comment]
> Hello. Is there any procedure to restart the m5stick in the library?

Hi

Have you tried

```ESP.restart()```
