### ISSUE TITLE
Interrupt Pin for IMU (Arduino)

### ISSUE THREAD

**Issue by jacob-fw** [m5stack/M5StickC#162]
I'm probably overlooking this in the code/documentation, but what is the pin the mpu uses to signal a data ready interrupt?  I see how to enable the interrupt in the mpu datasheet; just need to know which pin I attach the interrupt handler too.

**Comment by Tinyu-Zhao** [comment]
<img width="842" alt="image" src="https://github.com/m5stack/M5StickC/assets/44396641/b1e1172f-f00c-4a75-a443-4cfcb9a847e9">
 AXP192 -IRQ

**Comment by randybb** [comment]
gpio35 on esp32 is connected to all irq pins https://m5stack.oss-cn-shenzhen.aliyuncs.com/resource/docs/schematic/Core/M5StickC/20191118__StickC_A04_3110_Schematic_Rebuild_PinMap.pdf
