### ISSUE TITLE
Invalid Function Description

### ISSUE THREAD

**Issue by Kabron287** [m5stack/M5StickC#163]
I spent a day trying to understand this shameable BUG.
In docs page (https://docs.m5stack.com/en/api/stickc/axp192_m5stickc) function
**GetVapsData()** described as **Get battery capacity** while in datasheet the register 0x7E used
in this function corresponds to APS Voltage.

![Docs](https://user-images.githubusercontent.com/2493191/222965817-3b876719-c6b9-4e4e-b970-8bda8586bfa6.jpg)
![Datasheet](https://user-images.githubusercontent.com/2493191/222965827-98fe4c89-fd24-4595-b619-f0f8e9a097fb.jpg)

**Comment by Tinyu-Zhao** [comment]
Sorry, The error has been corrected.
