### ISSUE TITLE
Broken link from M5StickC 8-Channel Servo Driver HAT doc

### ISSUE THREAD

**Issue by lboue** [m5stack/M5StickC#165]
### Describe the bug

Hello,

I noticed a broken link from [M5StickC 8-Channel Servo Driver HAT doc](https://docs.m5stack.com/en/hat/hat_8servos_1.1)

8Servos HAT v1.1 with M5StickC : [8SERVO_V1.1.ino](https://github.com/m5stack/M5StickC/blob/master/examples/Hat/8SERVO_V1.1/8SERVO_V1.1.ino)

Could you fix it?

Regards

### To reproduce

Go to [M5StickC 8-Channel Servo Driver HAT doc](https://docs.m5stack.com/en/hat/hat_8servos_1.1) click the _8Servos HAT v1.1 with M5StickC_ link.

### Expected behavior

Download 8SERVO_V1.1.ino file

### Environment

- OS:
- IDE &IDE Version:
- Repository Version:

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/m5stack/M5StickC-Plus/issues?q=)
- [X] My report contains all necessary details

### To reproduce

https://github.com/m5stack/M5StickC/blob/master/examples/Hat/8SERVO_V1.1/8SERVO_V1.1.ino

### Expected behavior

Download 8SERVO_V1.1.ino file

### Environment

- OS:
- IDE &IDE Version:
- Repository Version:

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/m5stack/M5StickC/issues?q=)
- [X] My report contains all necessary details

**Comment by Tinyu-Zhao** [comment]
[Fixed](https://docs.m5stack.com/en/hat/hat_8servos_1.1), thank you for your help!
