### ISSUE TITLE
v0.2.9 fails to install in Arduino v2.2.1: Failed to install library.

### ISSUE THREAD

**Issue by GavinBeattie** [m5stack/M5StickC#168]
### Describe the bug

From Update button:
Failed to install library: M5StcikC: 0.2.9 No valid dependencies found. Dependency M5_JoyC is not available.

### To reproduce

macOS + Windows10
Arduino IDE v2.2.1

### Expected behavior

Normally updates take care of themselves almost in the background.

### Environment

- OS:
- IDE &IDE Version:
- Repository Version:

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/m5stack/M5StickC/issues?q=)
- [X] My report contains all necessary details

**Comment by mrsav25** [comment]
Looks like they changed the library name as I'm trying the same thing right now, but no idea how to work around that: https://github.com/m5stack/M5Hat-JoyC
