### ISSUE TITLE
Deep Sleep and Display

### ISSUE THREAD

**Issue by bert2002** [m5stack/M5StickC#2]
Hi,
it seems that the deep sleep mode does not shut down the display. When using following code the display stays on:

```
esp_sleep_enable_timer_wakeup(60000000);
esp_deep_sleep_start();
```
Is there anything we can do about?

bert

**Comment by bert2002** [comment]
I see that I can disable the display while booting, but even then the backlight gets on.

Reference: https://docs.m5stack.com/#/en/api/system_m5stickc

**Comment by bert2002** [comment]
Mhmm seems that Wifi also does not get disabled, even if I use this:
```
esp_sleep_pd_config(ESP_PD_DOMAIN_RTC_SLOW_MEM, ESP_PD_OPTION_OFF);
esp_sleep_pd_config(ESP_PD_DOMAIN_RTC_FAST_MEM, ESP_PD_OPTION_OFF);
esp_sleep_pd_config(ESP_PD_DOMAIN_RTC_PERIPH, ESP_PD_OPTION_OFF);
```

**Comment by EeeeBin** [comment]
Display Lcd is control by axp192, ldo2, Try call this fun https://github.com/m5stack/M5StickC/blob/master/src/AXP192.cpp#L372

**Comment by bert2002** [comment]
How do I call this @EeeeBin ?

**Comment by EeeeBin** [comment]
```M5.Axp.SetSleep()``` Called in front of deep sleep

**Comment by bert2002** [comment]
Seems my library does not have the SetSleep() function, but I got it working with this:
```
esp_sleep_pd_config(ESP_PD_DOMAIN_RTC_SLOW_MEM, ESP_PD_OPTION_OFF);
esp_sleep_pd_config(ESP_PD_DOMAIN_RTC_FAST_MEM, ESP_PD_OPTION_OFF);
esp_sleep_pd_config(ESP_PD_DOMAIN_RTC_PERIPH, ESP_PD_OPTION_OFF);
```

**Comment by anthonykeane** [comment]
> `M5.Axp.SetSleep()` Called in front of deep sleep

is it possible to wake from this with a button press or timer?

**Comment by bert2002** [comment]
> > `M5.Axp.SetSleep()` Called in front of deep sleep
> 
> @bert2002 is it possible to wake from this with a button press or timer?

I didn't try it, but I saw an implementation in the M5Stack Firmware, which was not available in the M5StickC implementation. Then I stopped looking into it.

**Comment by jumpjack** [comment]
M5.Lcd.writecommand(ST7735_DISPOFF); // Turn off screen, but not backlight
(https://community.m5stack.com/topic/94/turn-off-display/6 )

  M5.Axp.ScreenBreath(0); // Turn off backlight
