### ISSUE TITLE
Add a Microphone demo

### ISSUE THREAD

**Issue by alfem** [m5stack/M5StickC#4]
I would like to use this wristwatch wearable to record my voice and send it to a home server, in order to do some voice recognition and home automation.

But I can not find any example code about the SPM1423.

Any clue would be welcome.

**Comment by zhouyangyale** [comment]
https://github.com/m5stack/M5StickC/tree/master/examples/Basics/Micophone

**Comment by alfem** [comment]
Oops! I searched for "microphone" and I am afraid there is a little typo in your repo. It sais "micophone"
