### ISSUE TITLE
UNIT_LIGHT - Wrong INPUT PIN

### ISSUE THREAD

**Issue by WhistleMaster** [m5stack/M5StickC#43]
https://github.com/m5stack/M5StickC/blob/93f41895dd4ea64fc43e80e75ceaa3cf5b240421/examples/Unit/Light/Light.ino#L12

Should be `pinMode(32, INPUT);`

**Comment by EeeeBin** [comment]
Fixed https://github.com/m5stack/M5StickC/commit/52ed0ec92091f28d2662e05a58fe795c49eeb360
