### ISSUE TITLE
Default AXP192 charging current

### ISSUE THREAD

**Issue by 49616e** [m5stack/M5StickC#44]
According the datasheet of AXP192, it's currently configured to charge the battery at 190mA (in AXP192.cpp), which is a bit too much for an 80mAh cell. Would you consider lowering the default to 100mA instead? It'll probably make the bettery last more cycles in the future.

**Comment by EeeeBin** [comment]
Updated on https://github.com/m5stack/M5StickC/commit/94a786b72051c1053b7f092911eab878e1c85db2

**Comment by 49616e** [comment]
Thanks for updating it.
