### ISSUE TITLE
RTC interrupt pin connected to ESP32 or not?

### ISSUE THREAD

**Issue by huming2207** [m5stack/M5StickC#45]
Hi there,

I would like to know that have you connected the BM8563 RTC chip's INT pin to ESP32 or not? It may be helpful for waking up or notifying the microcontroller.

Regards,
Jackson

**Comment by EeeeBin** [comment]
RTC INT pin connect to esp32 GPIO35

**Comment by huming2207** [comment]
@EeeeBin Thanks for your reply.

Same question again, what about the gyro's INT pin? Is it connected to ESP32?

**Comment by EeeeBin** [comment]
AXP192, IMU and RTC all connect to gpio35
![image](https://user-images.githubusercontent.com/24584225/63744683-a9dc8680-c8d2-11e9-8fa8-f24a8d0c3e61.png)

**Comment by huming2207** [comment]
@EeeeBin Thanks. I didn't find it out in the image.

**Comment by mmarsalko** [comment]
What about M5Stick variants that use the SH200Q IMU? I've not had luck waking up ESP32 on GPIO35

**Comment by mmarsalko** [comment]
@EeeeBin What about M5Stick variants that use the SH200Q IMU? I've not had luck waking up ESP32 on GPIO35 using the SH200's activity interrupts
