### ISSUE TITLE
microphone tests

### ISSUE THREAD

**Issue by beckmx** [m5stack/M5StickC#56]
Hello guys, I am not able to understand the microphone, is it a 16 bit resolution microphone?, additionally, I wanted to record voice but seems to not fully record all samples and loses quality

**Comment by EeeeBin** [comment]
And Sorry, we have no examples of recording sounds.
Microphone is PDM data out

**Comment by beckmx** [comment]
So the microphone is connected using I2S but data is PDM, is this right?

**Comment by EeeeBin** [comment]
I2S support read PDM data
https://docs.espressif.com/projects/esp-idf/en/latest/api-reference/peripherals/i2s.html?highlight=PDM#_CPPv414pdm_pcm_conv_t

**Comment by beckmx** [comment]
Found the way to get the conversion, thanx
