### ISSUE TITLE
Smooth fonts

### ISSUE THREAD

**Issue by vvs551** [m5stack/M5StickC#7]
Could you add Smooth font support for the internalization of the project?
Need to change In_eSPI.h and .cpp and set definition:
#define SMOOTH_FONT
[In_eSPI.zip](https://github.com/m5stack/M5StickC/files/3191130/In_eSPI.zip)

**Comment by vvs551** [comment]
Hi friends!

**Comment by EeeeBin** [comment]
Can you submit a PR :)
