### ISSUE TITLE
Display off with M5.Axp.SetSleep()

### ISSUE THREAD

**Issue by vvs551** [m5stack/M5StickC#8]
How to restore display from code after M5.Axp.SetSleep()?
As far as I see, M5.Axp.SetSleep() just switch off the display, but all other is working
I would like to restore the display with pressing the button

**Comment by zhouyangyale** [comment]
You can wake up by pressing the PEK button

**Comment by zhouyangyale** [comment]
Now we have added the function of automatic wakeup
