### ISSUE TITLE
M5StickC - Question

### ISSUE THREAD

**Issue by markbirss** [m5stack/M5StickC#84]
Where to connect RX,TX on M5StickC ?

**Comment by EeeeBin** [comment]
All the output pins you can use
In StickC:
**tx:** 0, 32, 33, 26
 **rx:** 0, 32, 33, 26, 36

**Comment by markbirss** [comment]
@EeeeBin 

I connect to G26 , G36 and GND?

![image](https://user-images.githubusercontent.com/22388007/72135129-6b7dca80-338e-11ea-9272-ad8289ae2c86.png)

**Comment by EeeeBin** [comment]
```
  // Serial2.begin(unsigned long baud, uint32_t config, int8_t rxPin, int8_t txPin, bool invert)
  Serial2.begin(115200, SERIAL_8N1, 36, 26);
```

**Comment by markbirss** [comment]
Ah ok, thank you for your feedback
