### ISSUE TITLE
MacOs trouble with connection

### ISSUE THREAD

**Issue by maxsimak** [m5stack/M5StickC#86]
There are some problems when flashing Arduino projects (a fatal error occurred: failed to connect to ESP32: invalid packet header (0x4F)) Download speed and board are correct. When I flash in Ui Flow the exact same problem. Drivers set from quick guide. How fix this?
<img width="869" alt="Снимок экрана 2020-01-15 в 01 36 51" src="https://user-images.githubusercontent.com/33913201/72388634-83ab6c00-3737-11ea-957c-44a72a0dfce6.png">

**Comment by EeeeBin** [comment]
Maybe same as https://github.com/m5stack/M5StickC/issues/77
Detail please contact after-sales of M5

**Comment by maxsimak** [comment]
Maybe there is some other solution. I would not like to make a refund

**Comment by maxsimak** [comment]
M5 StickC works correctly, but the problem with the drivers on the Mac .If you have friends with Windows 10 PC or BootCamp (work without drivers) then flash in M5 Burner Ui Flow and use it in Cloud mode

**Comment by masrodjie** [comment]
Please check this https://forum.m5stack.com/topic/1591/m5stickc-atom-on-macos-catalina-can-t-upload-esp32-timed-out-waiting-for-packet-header-solution
It's works on me
